### ISSUE TITLE
Transcript typeの追加

### ISSUE THREAD

**Issue by mitsuhashi** [biosciencedbc/rdf-ensembl_grch38#1]
Transcript typeも取り込むようにコンバータが更新されたので対応をお願いできないでしょうか。

Transcript typeは、[３つあるinputファイル](https://github.com/skwsm/rdf_converter_ensembl_human_grch37#input-files)の１番目の一番最後の列です。

BioMartでのAttribute_nameは"transcript_biotype" になります。
http://asia.ensembl.org/biomart/martview/a4ec939b1e1160cfc40edbccb50bc33c

https://github.com/biosciencedbc/rdf-ensembl_grch38/blob/master/convert_ensembl#L67
に追加かなというのは何となくわかりますが、お願いした方が確実かと思いましたので、よろしくお願いします。

GRCh37の方も対応をお願いいたします。

**Comment by sakon-hi** [comment]
@mitsuhashi  GRCh37 も含めて、修正を反映しました。
https://github.com/biosciencedbc/rdf-ensembl_grch38/commit/a64a5f64329d826c92a30d5ea81b5e32bd9754a3
https://github.com/biosciencedbc/rdf-ensembl_grch37/commit/4f90958dbeb4c07e62fa14b92f362d4bfad779e4

**Comment by mitsuhashi** [comment]
@sakon-hi どうもありがとうございます。ログにはensembl_grch38 の更新はありません、のメッセージがあって、6/15,6/16との差分がないので反映できていないようです。強制実行することはできますでしょうか。
```
[mitsuhashi@smp06 ensembl_grch38]$ ls
20211105  20211210  20220203  20220204  20220331  20220412  20220519  20220615  20220616  20220620  latest
[mitsuhashi@smp06 ensembl_grch38]$ diff 20220615/ensembl.ttl 20220620/ensembl.ttl
[mitsuhashi@smp06 ensembl_grch38]$ diff 20220616/ensembl.ttl 20220620/ensembl.ttl
```

**Comment by sakon-hi** [comment]
@mitsuhashi 

2022/6/20の実行では
https://github.com/biosciencedbc/rdf-ensembl_grch38/commit/a64a5f64329d826c92a30d5ea81b5e32bd9754a3 の修正により、「コンバータソースコード変更あり」と判定され、コンバート処理が実施されましたが、
オリジナルの Ensemblのデータの Version自体は更新されていないので、 BioMart経由でのデータの再ダウンロードは「不要」と判定されています。そのためサーバにダウンロード済みのEnsemblのデータが使用されたようです。

BioMart経由で強制的にデータを再取得したい場合、ダウンロード済みのオリジナルデータを削除して再実行が必要なようです。
この後、再実行を実施します。（grch38, grch37両方とも）

**Comment by mitsuhashi** [comment]
@biosciencedbc/hitachi-togovar 
想定したturtleファイルが作成されていることを確認しました。クローズします。ありがとうございました。
```
[mitsuhashi@smp06 latest]$ grep -A 5 -B 5 SO_0000234 ensembl.ttl | head -20
            faldo:reference <http://identifiers.org/hco/MT#GRCh37> ;
        ]
    ] .

enst:ENST00000361390 a term:protein_coding ;
    a ens:SO_0000234 ;
    dcterms:identifier "ENST00000361390" ;
    rdfs:label "MT-ND1-201" ;
    obo:BFO_0000050 ens:ENSG00000198888 ;
    so:part_of ens:ENSG00000198888 ;
    so:transcribed_from ens:ENSG00000198888 ;
--
```
